In [1]:
#Q1:Some facilities charge memebership fee and some doesn't, write a SQL to show the name of facilities that do
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT name
        FROM Facilities
        Where membercost!=0
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 1',)
('Tennis Court 2',)
('Massage Room 1',)
('Massage Room 2',)
('Squash Court',)

In [2]:
#2 How many facilities do not charge memebership fee
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT COUNT(name)
        FROM Facilities
        Where membercost==0
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(4,)

In [3]:
# Q3: Write a Query to show the name of facility that charge memeber fee, where the fee is less than 20% of maintainence fee. Show the facid, facility name,memeber cost and monthly maintenance
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT facid, name, membercost,monthlymaintenance
        FROM Facilities
        Where membercost!=0 AND membercost<0.2*monthlymaintenance
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 5, 200)
(1, 'Tennis Court 2', 5, 200)
(4, 'Massage Room 1', 9.9, 3000)
(5, 'Massage Room 2', 9.9, 3000)
(6, 'Squash Court', 3.5, 80)

In [4]:
#Q4 
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT * 
        FROM Facilities 
        WHERE Facid IN (1,5) 
        ORDER BY `Facilities`.`facid` ASC
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(1, 'Tennis Court 2', 5, 25, 8000, 200)
(5, 'Massage Room 2', 9.9, 80, 4000, 3000)

In [5]:
#Q5 Produce a list of facilities which labeled as 'cheap' or 'expensive' depend whether monthly cost is more than $100, return name and monthly maintenance
import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT name, monthlymaintenance, 
        CASE WHEN monthlymaintenance>100 THEN 'Expensive'
        ELSE 'Cheap'
        END AS 'Cheap or Expensive'
        FROM Facilities 
        
        ORDER BY `Facilities`.`facid` ASC
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 1', 200, 'Expensive')
('Tennis Court 2', 200, 'Expensive')
('Badminton Court', 50, 'Cheap')
('Table Tennis', 10, 'Cheap')
('Massage Room 1', 3000, 'Expensive')
('Massage Room 2', 3000, 'Expensive')
('Squash Court', 80, 'Cheap')
('Snooker Table', 15, 'Cheap')
('Pool Table', 15, 'Cheap')

In [6]:
#Q6 You would like to have the first and last name of last member(s) who sign up. Try not use limit

import sqlite3
from sqlite3 import Error
 
def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
        SELECT firstname, surname, joindate 
        FROM Members 
        ORDER BY joindate DESC
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
 
    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Darren', 'Smith', '2012-09-26 18:08:45')
('Erica', 'Crumpet', '2012-09-22 08:36:38')
('John', 'Hunt', '2012-09-19 11:32:45')
('Hyacinth', 'Tupperware', '2012-09-18 19:32:05')
('Millicent', 'Purview', '2012-09-18 19:04:01')
('Henry', 'Worthington-Smyth', '2012-09-17 12:27:15')
('David', 'Farrell', '2012-09-15 08:22:05')
('Henrietta', 'Rumney', '2012-09-05 08:42:35')
('Douglas', 'Jones', '2012-09-02 18:43:05')
('Ramnaresh', 'Sarwin', '2012-09-01 08:44:42')
('Joan', 'Coplin', '2012-08-29 08:32:41')
('Anna', 'Mackenzie', '2012-08-26 09:32:05')
('Matthew', 'Genting', '2012-08-19 14:55:55')
('David', 'Pinker', '2012-08-16 11:32:47')
('Timothy', 'Baker', '2012-08-15 10:34:25')
('Florence', 'Bader', '2012-08-10 17:52:03')
('Jack', 'Smith', '2012-08-10 16:22:05')
('Jemima', 'Farrell', '2012-08-10 14:28:01')
('Anne', 'Baker', '2012-08-10 14:23:22')
('David', 'Jones', '2012-08-06 16:32:55')
('Charles', 'Owen', '2012-08-03 19:42:37')
('Ponder', 'Stibbons', '2012-07-25 17:09:05')
('Tim', 'Boothe', '2012-07-25 16:02:35')
('Nancy', 'Dare', '2012-07-25 08:59:12')
('Burton', 'Tracy', '2012-07-15 08:52:55')
('Gerald', 'Butters', '2012-07-09 10:44:09')
('Janice', 'Joplette', '2012-07-03 10:25:05')
('Tim', 'Rownam', '2012-07-03 09:32:15')
('Tracy', 'Smith', '2012-07-02 12:08:23')
('Darren', 'Smith', '2012-07-02 12:02:05')
('GUEST', 'GUEST', '2012-07-01 00:00:00')

In [7]:
#Q7 produce a list of memebers who use the tennis court, include the name of court and the name of member in a single column
import sqlite3
from sqlite3 import Error
from pandas import DataFrame

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    query1 = """
        SELECT name, firstname || "," || surname AS fullname
        FROM Facilities f
        INNER JOIN Bookings b ON f.facid = b.facid
        INNER JOIN Members m ON b.memid = m.memid
        WHERE b.facid IN ( 0, 1 )
        ORDER BY surname

        """
    cur.execute(query1)
 
    rows = cur.fetchall()
#    df = DataFrame(rows,columns=['Tennis Court','firstname','surname'])
#    print(df)
    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Tennis Court 2', 'Florence,Bader')
('Tennis Court 2', 'Florence,Bader')
('Tennis Court 2', 'Florence,Bader')
('Tennis Court 2', 'Florence,Bader')
('Tennis Court 2', 'Florence,Bader')
('Tennis Court 2', 'Florence,Bader')
('Tennis Court 2', 'Florence,Bader')
('Tennis Court 1', 'Florence,Bader')
('Tennis Court 2', 'Florence,Bader')
('Tennis Court 1', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 1', 'Anne,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Timothy,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 1', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Timothy,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 1', 'Anne,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 1', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Timothy,Baker')
('Tennis Court 1', 'Anne,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 1', 'Timothy,Baker')
('Tennis Court 2', 'Anne,Baker')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 1', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 1', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 1', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 1', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 2', 'Tim,Boothe')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 2', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 2', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 2', 'Gerald,Butters')
('Tennis Court 1', 'Gerald,Butters')
('Tennis Court 1', 'Joan,Coplin')
('Tennis Court 1', 'Joan,Coplin')
('Tennis Court 1', 'Joan,Coplin')
('Tennis Court 1', 'Joan,Coplin')
('Tennis Court 1', 'Joan,Coplin')
('Tennis Court 1', 'Joan,Coplin')
('Tennis Court 1', 'Joan,Coplin')
('Tennis Court 1', 'Erica,Crumpet')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 2', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 1', 'Nancy,Dare')
('Tennis Court 2', 'Jemima,Farrell')
('Tennis Court 1', 'Jemima,Farrell')
('Tennis Court 1', 'David,Farrell')
('Tennis Court 1', 'David,Farrell')
('Tennis Court 1', 'David,Farrell')
('Tennis Court 1', 'David,Farrell')
('Tennis Court 2', 'David,Farrell')
('Tennis Court 1', 'David,Farrell')
('Tennis Court 1', 'David,Farrell')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 1', 'GUEST,GUEST')
('Tennis Court 2', 'GUEST,GUEST')
('Tennis Court 1', 'Matthew,Genting')
('Tennis Court 1', 'John,Hunt')
('Tennis Court 2', 'John,Hunt')
('Tennis Court 1', 'John,Hunt')
('Tennis Court 2', 'John,Hunt')
('Tennis Court 2', 'John,Hunt')
('Tennis Court 2', 'John,Hunt')
('Tennis Court 1', 'John,Hunt')
('Tennis Court 1', 'John,Hunt')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'Douglas,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'Douglas,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'Douglas,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'Douglas,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'Douglas,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'Douglas,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'Douglas,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'Douglas,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 1', 'Douglas,Jones')
('Tennis Court 1', 'David,Jones')
('Tennis Court 2', 'David,Jones')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 2', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 2', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 2', 'Janice,Joplette')
('Tennis Court 2', 'Janice,Joplette')
('Tennis Court 2', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 2', 'Janice,Joplette')
('Tennis Court 2', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 2', 'Janice,Joplette')
('Tennis Court 1', 'Janice,Joplette')
('Tennis Court 1', 'Charles,Owen')
('Tennis Court 1', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 1', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 1', 'Charles,Owen')
('Tennis Court 1', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 1', 'Charles,Owen')
('Tennis Court 1', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 1', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')
('Tennis Court 1', 'Charles,Owen')
('Tennis Court 1', 'Charles,Owen')
('Tennis Court 2', 'Charles,Owen')

In [8]:
#Q8 produce a list of booking on the day of 2012-09-14, which will cost memeber or gust more than $30
# remember that memeber and guest have different price. The cost are half hour per slot and guest userid is usually 0
# output: name of facilities, memeber formatted in a single column, the descending order of cost, do not use subquery
import sqlite3
from sqlite3 import Error
from pandas import DataFrame

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    query1 = """
    SELECT m.firstname || ' ' || m.surname AS fullname, b.starttime,
    CASE WHEN m.memid = 0 THEN (f.guestcost * b.slots)
    ELSE (f.membercost * b.slots)
    END AS cost, f.name
    FROM Members m
    LEFT JOIN Bookings b ON m.memid = b.memid
    LEFT JOIN Facilities f ON b.facid = f.facid
    WHERE b.starttime LIKE '2012-09-14%'
    AND IIF(m.memid =0, f.guestcost, f.membercost) * b.slots > 30
    ORDER BY cost DESC    
        """
    cur.execute(query1)
 
    rows = cur.fetchall()

    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('GUEST GUEST', '2012-09-14 11:00:00', 320, 'Massage Room 2')
('GUEST GUEST', '2012-09-14 09:00:00', 160, 'Massage Room 1')
('GUEST GUEST', '2012-09-14 13:00:00', 160, 'Massage Room 1')
('GUEST GUEST', '2012-09-14 16:00:00', 160, 'Massage Room 1')
('GUEST GUEST', '2012-09-14 17:00:00', 150, 'Tennis Court 2')
('GUEST GUEST', '2012-09-14 16:00:00', 75, 'Tennis Court 1')
('GUEST GUEST', '2012-09-14 19:00:00', 75, 'Tennis Court 1')
('GUEST GUEST', '2012-09-14 14:00:00', 75, 'Tennis Court 2')
('GUEST GUEST', '2012-09-14 09:30:00', 70.0, 'Squash Court')
('Jemima Farrell', '2012-09-14 14:00:00', 39.6, 'Massage Room 1')
('GUEST GUEST', '2012-09-14 12:30:00', 35.0, 'Squash Court')
('GUEST GUEST', '2012-09-14 15:00:00', 35.0, 'Squash Court')

In [9]:
# Q9 Q* with subquery
# remember that memeber and guest have different price. The cost are half hour per slot and guest userid is usually 0
# output: name of facilities, total revenue on descending order


import sqlite3
from sqlite3 import Error
from pandas import DataFrame

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    query1 = """
    SELECT t1.fname, m.firstname || ' ' || m.surname AS fullname, t1.cost
    FROM (
    SELECT f.name AS fname,
    CASE WHEN b.memid =0
    THEN (
    f.guestcost * b.slots
    )
    ELSE (
    f.membercost * b.slots
    )
    END AS cost, 
    b.starttime AS bstarttime, 
    b.memid AS bmemid
    FROM Facilities f
    LEFT JOIN Bookings b ON f.facid = b.facid
    WHERE (
    b.memid !=0 AND f.membercost * b.slots >30
    )
    OR (
    b.memid ==0 AND f.guestcost * b.slots >30
    )
    ORDER BY cost DESC
    ) AS t1
    LEFT JOIN Members m ON t1.bmemid = m.memid
    WHERE t1.bstarttime LIKE '2012-09-14%'
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
#    df = DataFrame(rows,columns=['Tennis Court','firstname','surname'])
#    print(df)
    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Massage Room 2', 'GUEST GUEST', 320)
('Massage Room 1', 'GUEST GUEST', 160)
('Massage Room 1', 'GUEST GUEST', 160)
('Massage Room 1', 'GUEST GUEST', 160)
('Tennis Court 2', 'GUEST GUEST', 150)
('Tennis Court 1', 'GUEST GUEST', 75)
('Tennis Court 1', 'GUEST GUEST', 75)
('Tennis Court 2', 'GUEST GUEST', 75)
('Squash Court', 'GUEST GUEST', 70.0)
('Massage Room 1', 'Jemima Farrell', 39.6)
('Squash Court', 'GUEST GUEST', 35.0)
('Squash Court', 'GUEST GUEST', 35.0)

In [10]:
#Q10 product a list of facility where the total revenue was less than 1000. 
# remember that memeber and guest have different price. The cost are half hour per slot and guest userid is usually 0
# output: name of facilities, total revenue on descending order
import sqlite3
from sqlite3 import Error
from pandas import DataFrame

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    query1 = """
    SELECT name, revenue
    FROM (
    SELECT name, SUM(
    CASE WHEN memid =0
    THEN guestcost * slots
    ELSE membercost * slots
    END ) AS revenue
    FROM Bookings b
    INNER JOIN Facilities f ON b.facid = f.facid
    GROUP BY name
    ) AS inner_table
    WHERE revenue <1000
    ORDER BY revenue
        """
    cur.execute(query1)
 
    rows = cur.fetchall()
#    df = DataFrame(rows,columns=['Tennis Court','firstname','surname'])
#    print(df)
    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 180)
('Snooker Table', 240)
('Pool Table', 270)

In [11]:
#Q11 produce a list of memebers and who recommended them in alphebitic surname order

import sqlite3
from sqlite3 import Error
from pandas import DataFrame

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    
    query1 = """
    SELECT m.firstname || ',' || m.surname AS Recommended_By,
    rcmd.firstname || ',' || rcmd.surname AS Member
    FROM Members m
    inner join Members rcmd on rcmd.recommendedby = m.memid
    WHERE m.memid > 0
    order by m.surname,m.firstname,rcmd.surname,rcmd.surname
    """
    cur.execute(query1)
 
    rows = cur.fetchall()

    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Florence,Bader', 'Ramnaresh,Sarwin')
('Timothy,Baker', 'Joan,Coplin')
('Gerald,Butters', 'Matthew,Genting')
('Jemima,Farrell', 'Timothy,Baker')
('Jemima,Farrell', 'David,Pinker')
('Matthew,Genting', 'Henrietta,Rumney')
('David,Jones', 'Douglas,Jones')
('Janice,Joplette', 'Nancy,Dare')
('Janice,Joplette', 'David,Jones')
('Millicent,Purview', 'John,Hunt')
('Tim,Rownam', 'Tim,Boothe')
('Darren,Smith', 'Gerald,Butters')
('Darren,Smith', 'Janice,Joplette')
('Darren,Smith', 'Anna,Mackenzie')
('Darren,Smith', 'Charles,Owen')
('Darren,Smith', 'Jack,Smith')
('Tracy,Smith', 'Erica,Crumpet')
('Tracy,Smith', 'Millicent,Purview')
('Tracy,Smith', 'Henry,Worthington-Smyth')
('Ponder,Stibbons', 'Florence,Bader')
('Ponder,Stibbons', 'Anne,Baker')
('Burton,Tracy', 'Ponder,Stibbons')

In [12]:
#Q12 Find Facilities where its usage by member, not guest

import sqlite3
from sqlite3 import Error
from pandas import DataFrame

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT b.facid, f.name, COUNT( slots )
    FROM Bookings b
    LEFT JOIN Facilities f ON b.facid = f.facid
    WHERE memid !=0
    GROUP BY b.facid
    """
    cur.execute(query1)
 
    rows = cur.fetchall()

    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
(0, 'Tennis Court 1', 308)
(1, 'Tennis Court 2', 276)
(2, 'Badminton Court', 344)
(3, 'Table Tennis', 385)
(4, 'Massage Room 1', 421)
(5, 'Massage Room 2', 27)
(6, 'Squash Court', 195)
(7, 'Snooker Table', 421)
(8, 'Pool Table', 783)

In [13]:
#Q13 Find Facilities where its usage by member, not guest

import sqlite3
from sqlite3 import Error
from pandas import DataFrame

def create_connection(db_file):
    """ create a database connection to the SQLite database
        specified by the db_file
    :param db_file: database file
    :return: Connection object or None
    """
    conn = None
    try:
        conn = sqlite3.connect(db_file)
        print(sqlite3.version)
    except Error as e:
        print(e)
 
    return conn
 
def select_all_tasks(conn):
    """
    Query all rows in the tasks table
    :param conn: the Connection object
    :return:
    """
    cur = conn.cursor()
    
    query1 = """
    SELECT f.name, COUNT( b.slots )
    FROM Bookings b
    LEFT JOIN Facilities f ON b.facid = f.facid
    WHERE b.memid !=0
    GROUP BY strftime('%m', b.starttime)
    """
    cur.execute(query1)
 
    rows = cur.fetchall()

    for row in rows:
        print(row)


def main():
    database = "C:\\Users\\mohua\\OneDrive\\Documents\\unit6\\sqlite\\db\\pythonsqlite.db"
 
    # create a database connection
    conn = create_connection(database)
    with conn: 
        print("2. Query all tasks")
        select_all_tasks(conn)
 
 
if __name__ == '__main__':
    main()

2.6.0
2. Query all tasks
('Table Tennis', 480)
('Tennis Court 1', 1168)
('Tennis Court 1', 1512)